DisplaySweet/core/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'^$', 'core.views.index', name='home'),
    url(r'^404/$', 'core.views.force_404', name='404'),
)

DisplaySweet/users/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from rest_framework.authtoken.models import Token as AuthToken
import datetime
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from core.models import Project
from core.permissions import ClientPermissionsMixin
from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from users.permissions import AllocationDetailsPermissionMixin
import smtplib
import string
import urllib
import random
from .smtp_email import send_smpt_email
from projects.models.model_mixin import PrimaryModelMixin
from projects.cms_sync import ProjectCMSSync


class UserManager(BaseUserManager):
    def create_user(self, username, first_name, last_name, email, user_type=None, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError('Users must have a username')

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )

        if user_type:
            user.user_type = user_type

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, first_name, last_name, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(username, first_name, last_name, email, user_type=User.USER_TYPE_SUPER_ADMIN, password=password)

        user.can_access_django_backend = True
        user.status = User.APPROVED
        user.save(using=self._db)

        return user


class User(AllocationDetailsPermissionMixin, AbstractBaseUser):

    MR = 'Mr'
    MS = 'Ms'
    MRS = 'Mrs'
    DR = 'Dr'
    MISS = 'Miss'

    TITLE_OPTIONS = (
        (MS, 'Ms'),
        (MR, 'Mr'),
        (MRS, 'Mrs'),
        (MISS, 'Miss'),
        (DR, 'Dr'),
    )

    PRE_APPROVED = 'pending_registration'
    SUSPENDED = 'suspended'
    APPROVED = 'approved'

    STATUS_CHOICES = (
        (PRE_APPROVED, 'Pending Approval'),
        (SUSPENDED, 'Suspended'),
        (APPROVED, 'Approved'),
    )

    USER_TYPE_SUPER_ADMIN = 'super_admin_user'
    USER_TYPE_ADMIN = 'admin_user'

    USER_TYPE_CLIENT_ADMIN = 'client_admin_user'
    USER_TYPE_MASTER_AGENT = 'master_agent'
    USER_TYPE_AGENT = 'agent'
    USER_TYPE_VIEW_ONLY_USER = 'normal_user'

    USER_TYPE_CHOICES = (
        (USER_TYPE_SUPER_ADMIN, 'Display Sweet Super Admin'),
        (USER_TYPE_ADMIN, 'Display Sweet Admin'),
        (USER_TYPE_CLIENT_ADMIN, 'Client Admin'),
        (USER_TYPE_MASTER_AGENT, 'Master Agent'),
        (USER_TYPE_AGENT, 'Agent'),
        (USER_TYPE_VIEW_ONLY_USER, 'View Only User'),
    )

    CLIENT_ADMIN_USER_TYPE_CHOICES = (
        (USER_TYPE_MASTER_AGENT, 'Master Agent'),
        (USER_TYPE_AGENT, 'Agent'),
        (USER_TYPE_VIEW_ONLY_USER, 'View Only User'),
    )

    CLIENT_ADMIN_CHOICES = [USER_TYPE_MASTER_AGENT, USER_TYPE_AGENT, USER_TYPE_VIEW_ONLY_USER]

    MASTER_AGENT_USER_TYPE_CHOICES = (
        (USER_TYPE_AGENT, 'Agent'),
        (USER_TYPE_VIEW_ONLY_USER, 'View Only User'),
    )

    MASTER_AGENT_CHOICES = [USER_TYPE_AGENT, USER_TYPE_VIEW_ONLY_USER]

    created = models.DateTimeField(null=True, blank=True, auto_now_add=True)

    username = models.CharField('username', max_length=255, unique=True,
        help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[validators.RegexValidator(r'^[\w.@+-]+$', 'Enter a valid username.', 'invalid')])

    #this is terrible but we have to sync details between apps inc password then send password info via an email :|
    temporary_setup_password = models.CharField(max_length=50, null=True, blank=True)

    title = models.CharField('title', choices=TITLE_OPTIONS, max_length=30, null=True, blank=True, help_text="Enter your title.")
    first_name = models.CharField('first name', max_length=30, null=True, blank=True, help_text="Enter your first name.")
    last_name = models.CharField('last name', max_length=30, null=True, blank=True, help_text="Enter your last name.")
    email = models.EmailField('email address', max_length=255, unique=True, help_text="Enter your email address.")
    phone_number = models.CharField(max_length=255, null=True, blank=True, help_text="Please enter a valid 10 digit phone number. "
                                                                                     "Please include area code i.e 03.")
    date_of_birth = models.DateField(null=True, blank=True, help_text="Date of birth")
    
    company_name = models.CharField(max_length=50, null=True, blank=True, help_text="Enter your company name.")
    website = models.CharField(max_length=50, null=True, blank=True, help_text="Enter your website.")
    
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES, default=USER_TYPE_VIEW_ONLY_USER)
    is_active = models.BooleanField(default=True)
    can_access_django_backend = models.BooleanField(default=False)

    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=APPROVED)
    projects = models.ManyToManyField(Project, blank=True, related_name="user_projects")

    created_by = models.ForeignKey("User", null=True, blank=True, related_name="user_created_by")
    owned_by = models.ForeignKey("User", null=True, blank=True, related_name="user_owned_by")
    last_modified_by = models.ForeignKey("User", null=True, blank=True, related_name="user_modified_by")

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    def __unicode__(self):
        return self.get_full_name()

    def delete(self, *args, **kwargs):
        new_sync = ProjectCMSSync()

        if self.is_master_agent:
            created_users = User.objects.filter(created_by=self, user_type=User.USER_TYPE_AGENT)

            for created_user in created_users:
                projects = created_user.project_users_list.all()
                for project in projects:
                    new_sync.remove_user_access_from_sync(project.pk, project.name, created_user.email)

                    UserModifiedLog.objects.create_log(created_user, None,
                                                       "Removed user access to project %s" % project.name)

                created_user.delete()

            projects = self.viewable_projects
            for project in projects:
                new_sync.remove_user_access_from_sync(project.pk, project.name, self.email)

                UserModifiedLog.objects.create_log(self, None,
                                                   "Removed user access to project %s" % project.name)

        super(User, self).delete(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        "Django admin function. Does the user have a specific permission?"
        return self.can_access_django_backend

    def has_module_perms(self, app_label):
        "Django admin function. Does the user have permissions to view the app `app_label`?"
        return self.can_access_django_backend

    @property
    def is_staff(self):
        return self.can_access_django_backend

    @property
    def property_list(self):
        return self.project_users_list.filter(active=True)

    @property
    def is_site_administrator(self):
        return self.user_type == self.USER_TYPE_SUPER_ADMIN

    @property
    def is_normal_user(self):
        return self.user_type == self.USER_TYPE_VIEW_ONLY_USER

    @property
    def is_admin_user(self):
        return self.user_type in [self.USER_TYPE_SUPER_ADMIN, self.USER_TYPE_ADMIN]

    @property
    def is_administrator(self):
        return self.user_type in [self.USER_TYPE_SUPER_ADMIN, self.USER_TYPE_ADMIN]

    @property
    def is_super_admin_user(self):
        return self.user_type in [self.USER_TYPE_SUPER_ADMIN, self.USER_TYPE_ADMIN]

    @property
    def is_master_agent(self):
        return self.user_type == self.USER_TYPE_MASTER_AGENT

    @property
    def is_super_admin(self):
        return self.user_type in [self.USER_TYPE_SUPER_ADMIN, self.USER_TYPE_ADMIN]

    @property
    def is_ds_admin(self):
        return self.user_type in [self.USER_TYPE_SUPER_ADMIN,
                                  self.USER_TYPE_ADMIN]

    @property
    def is_project_user(self):
        return self.user_type in [self.USER_TYPE_CLIENT_ADMIN,
                                  self.USER_TYPE_MASTER_AGENT,
                                  self.USER_TYPE_AGENT,
                                  self.USER_TYPE_VIEW_ONLY_USER]

    @property
    def is_low_access_project_user(self):
        return self.user_type in [self.USER_TYPE_MASTER_AGENT,
                                  self.USER_TYPE_AGENT,
                                  self.USER_TYPE_VIEW_ONLY_USER]

    @property
    def is_allocations_only_user(self):
        return self.user_type in self.CLIENT_ADMIN_CHOICES

    @property
    def is_client_admin(self):
        return self.user_type == self.USER_TYPE_CLIENT_ADMIN

    @property
    def is_agent(self):
        return self.user_type == self.USER_TYPE_AGENT

    @property
    def is_view_only_user(self):
        return self.user_type == self.USER_TYPE_VIEW_ONLY_USER

    @property
    def active_nice_display(self):
        if self.is_active:
            return '<i class="fa fa-check text-success"></i>'
        else:
            return '<i class="fa fa-close text-danger"></i>'

    @property
    def viewable_users(self):

        if self.is_ds_admin:

DisplaySweet/templates/account_setup.html
{% extends "base_internal.html" %}

{% block title %}{{ block.super }} - Home{% endblock %}

{% block nav %}
    {% include "includes/nav.html" with link='home' %}
{% endblock %}

{% block breadcrumbs %}
    <a class="header-breadcrumb active" href="#">
        Home
    </a>
{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="pull-left">
                <img src="/static/common/img/Displaysweet_long_01.png" style="max-width: 800px;"> <br><br>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-7 col-md-9 col-sm-12">
            <div class="card card-bordered style-default-dark">
                <div class="card-head">
                    <header>Welcome to the DisplaySweet CMS</header>
                    <div class="tools">
                        <div class="btn-group">
                            <a class="btn btn-icon-toggle btn-collapse pull-right"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </div>
                <div class="card-body style-default-bright">
                    {% if not error %}
                        {% if user %}
                            <h3>Hello {{ user.get_full_name }}!</h3>
                        {% endif %}

                        Please set up your account password details using the form below.

                        <form action method="post" enctype="multipart/form-data">
                        {% csrf_token %}


                            <div class="row">
                                <div class="col-sm-6">
                                    {% include "includes/field.html" with field=form.new_password1 %}
                                    {% include "includes/field.html" with field=form.new_password2 %}
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-like-process" value="Submit">Save Details</button>
                                </div>
                            </div>
                        </form>
                    {% else %}
                        <h4>The activation key has either been used or is invalid. Please contact our administrator at: <b>admin@displaysweet.com</b></h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

DisplaySweet/templates/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=1200, initial-scale=1">
    <title>{% block title %}Display Sweet{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="/static/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="/static/vendor/bootstrap/css/awesome-bootstrap-checkbox.css" rel="stylesheet">
    <link href="/static/vendor/font-awesome-4.5.0/css/font-awesome.css" rel="stylesheet">
    <link href="/static/common/css/jquery-ui.min.css" rel="stylesheet">

    <!-- Datatables -->
    <link href="/static/vendor/datatables/dmedia/css/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/static/vendor/datatables/extensions/ColVis/css/dataTables.colVis.css" rel="stylesheet">

    <link href="/static/vendor/pickadate/lib/compressed/themes/classic.css" rel="stylesheet">
    <link href="/static/vendor/pickadate/lib/compressed/themes/classic.date.css" rel="stylesheet">
    <link href="/static/vendor/pickadate/lib/compressed/themes/classic.time.css" rel="stylesheet">

    <link rel="stylesheet" href="/static/vendor/toastmessage/css/jquery.toastmessage.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href="/static/common/css/app.css" rel="stylesheet">

    {% block extra_head_files %}{% endblock %}
  </head>

  <body class="{% block body_classes %}{% endblock %}">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/static/common/js/jquery.min.js"></script>
    <script src="/static/vendor/toastmessage/js/jquery.toastmessage.js"></script>
    <script src="/static/common/js/jquery-ui.min.js"></script>
    <script src="/static/vendor/floatHead/jquery.floatThead.js"></script>

    {% block body_content %}{% endblock %}

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/datatables/dmedia/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendor/datatables/dmedia/js/dataTables.bootstrap.js"></script>
    <script src="/static/vendor/datatables/extensions/ColVis/js/dataTables.colVis.js"></script>
    <script src="/static/common/js/tables.js"></script>

    <script src="/static/common/js/app.js"></script>
    <script src="/static/common/js/nav.js"></script>

    <script src="/static/common/js/lemmon-slider.js"></script>

    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        });

        var getUrlParameter = function getUrlParameter(sParam) {
            var sPageURL = decodeURIComponent(window.location.search.substring(1)),
                sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');

                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : sParameterName[1];
                }
            }
        };
    </script>
    {% include "toastmessages_fragment.html" %}
  </body>
</html>

DisplaySweet/templates/base_internal.html
{% extends "new_base.html" %}

{% block body_classes %}ns-internal{% endblock %}

{% block body_content %}

    <div class="fixed-alerts"></div>

    {% block content %}{% endblock %}


    <script>
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };
    </script>
{% endblock %}

DisplaySweet/templates/new_base.html
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
		<title>DisplaySweet CMS</title>
		
		<!-- BEGIN META -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=0.8,maximum-scale=0.8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="HandheldFriendly" content="true">

		<meta name="keywords" content="selling, property, apartments, content management, display, sweet, display suite, ">
		<meta name="description" content="The greatest CMS in the world.">
        <link rel='shortcut icon' href='{{ STATIC_URL }}common/img/displaysweet_icon.ico' type='image/x-icon'>
		<!-- END META -->


        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="/static/common/css/theme/bootstrap.css" />
        <link type="text/css" rel="stylesheet" href="/static/common/css/theme/materialadmin.css" />

        <!-- Font Awesome -->
        <link href="/static/vendor/font-awesome-4.5.0/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" href="/static/common/css/colobox.css" />
        <link href="/static/common/css/jquery-ui.min.css" rel="stylesheet">
		<link type="text/css" rel="stylesheet" href="/static/common/css/theme/material-design-iconic-font.min.css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <link href="/static/vendor/toastmessage/css/jquery.toastmessage.css" rel="stylesheet">
        <link href="/static/common/css/app.css" rel="stylesheet">

        {% block extra_head_files %}{% endblock %}

		<!-- END STYLESHEETS -->

	</head>

	<body class="menubar-hoverable  menubar-first full-content " onload="zoom()">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/static/common/js/jquery.min.js"></script>
    <script src="/static/vendor/floatHead/jquery.floatThead.js"></script>
    <script src="/static/vendor/toastmessage/js/jquery.toastmessage.js"></script>
    <script src="/static/common/js/jquery-ui.min.js"></script>
    <script src="/static/common/js/jquery.panzoom.js"></script>



	<!-- BEGIN HEADER-->
	<header id="header" >
        <div class="headerbar">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="headerbar-left">
				<ul class="header-nav header-nav-options">
					<li class="header-nav-brand" >
						<div class="brand-holder">
							<a href="#">
								<span class="text-lg text-bold text-primary header-breadcrumb">
                                    {% block breadcrumbs %} {% endblock %}
                                </span>
							</a>
						</div>
					</li>
					<li>
						<a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
							<i class="fa fa-bars"></i>
						</a>
					</li>
				</ul>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="headerbar-right">
                <div class="pull-left" style="margin-top: 10px;"><h1 class="header-breadcrumb">{{ project.name }}
                    {% if request.user.is_ds_admin %}<small><em>[V{{ project.version }}]</em></small>{% endif %}</h1></div>

                    <div style="display: inline-block; text-align: right; margin-right: 45px;">
                        <div style="margin-top: 12px;">
                            &nbsp;
                            <img style="height: 30px; width: auto; margin: 5px; margin-right: 0;" src="/static/common/img/displaysweet_logo_1.jpg" alt="" />
                            &nbsp;
                            <span class="profile-info">
                                <span class="bold-text black">{{ request.user.get_full_name }}</span> &nbsp; [{{ request.user.get_user_type_display }}]
                            </span>
                        </div>
                    </div>

                <!--end .dropdown -->
				<!--end .header-nav-profile -->
{#				<ul class="header-nav header-nav-toggle">#}
{#					<li>#}
{#						<a class="btn btn-icon-toggle btn-default" href="#offcanvas-search" data-toggle="offcanvas" data-backdrop="false">#}
{#							<i class="fa fa-ellipsis-v"></i>#}
{#						</a>#}
{#					</li>#}
{#				</ul><!--end .header-nav-toggle -->#}
			</div><!--end #header-navbar-collapse -->
		</div>

	</header>
	<!-- END HEADER-->

    {% include "toastmessages_fragment.html" %}

	<!-- BEGIN BASE-->
	<div id="base">
		<!-- BEGIN OFFCANVAS LEFT -->
		<div class="offcanvas">
        </div><!--end .offcanvas-->
		<!-- END OFFCANVAS LEFT -->

		<!-- BEGIN CONTENT-->
		<div id="content">
            <section class="style-default-bright" style="background: #e6e5e5 !important;">
                <div class="section-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12" id="main-content">
                            {% block body_content %}{% endblock %}
                        </div>
                    </div>
                </div><!--end .section-body -->
            </section>
		</div>
		<!-- END CONTENT -->

		<!-- BEGIN MENUBAR-->
		<div id="menubar" class="menubar-inverse ">
			<div class="menubar-fixed-panel">
				<div>
					<a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
						<i class="fa fa-bars"></i>
					</a>
				</div>
				<div class="expanded">
					<a href="{% url 'home' %}">
						<span class="text-lg text-bold text-primary ">DISPLAY&nbsp;SWEET</span>
					</a>
				</div>
			</div>
			<div class="menubar-scroll-panel">
				<!-- BEGIN MAIN MENU -->
                {% block nav %}
                    {% include "includes/nav.html" %}
                {% endblock %}
				<!-- END MAIN MENU -->

				<div class="menubar-foot-panel">
					<small class="no-linebreak hidden-folded">
						<span class="opacity-75">Copyright &copy; 2016</span> <strong>Display Sweet</strong>
					</small>
				</div>
			</div><!--end .menubar-scroll-panel-->
		</div><!--end #menubar-->
		<!-- END MENUBAR -->

		<!-- BEGIN OFFCANVAS RIGHT -->
        {% ifequal 1 0 %}
		<div class="offcanvas">
            <!-- BEGIN OFFCANVAS SEARCH -->
            <div id="offcanvas-search" class="offcanvas-pane width-8">
                <div class="offcanvas-head">
                    <header class="text-primary">Search</header>
                    <div class="offcanvas-tools">
                        <a class="btn btn-icon-toggle btn-default-light pull-right" data-dismiss="offcanvas">
                            <i class="fa fa-close"></i>
                        </a>
                    </div>
                </div>


                    <div class="offcanvas-body no-padding">
                        <ul class="list ">
                            <li class="tile divider-full-bleed">
                                <div class="tile-content">
                                    <div class="tile-text"><strong>Hello!</strong></div>
                                </div>
                            </li>
                            <li class="tile">
                                <a class="tile-content ink-reaction" href="#offcanvas-chat" data-toggle="offcanvas" data-backdrop="false">
                                    <div class="tile-icon">
                                        <img src="/static/common/img/user_avatar.png" alt="" />
                                    </div>
                                    <div class="tile-text">
                                        Some sidebar details here ;)
                                        <small>123-123-3210</small>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div><!--end .offcanvas-body -->

            </div><!--end .offcanvas-pane -->
            <!-- END OFFCANVAS SEARCH -->

            <!-- BEGIN OFFCANVAS CHAT -->
            <div id="offcanvas-chat" class="offcanvas-pane style-default-light width-12">
                <div class="offcanvas-head style-default-bright">
                    <header class="text-primary">Chat with Ann Laurens</header>
                    <div class="offcanvas-tools">
                        <a class="btn btn-icon-toggle btn-default-light pull-right" data-dismiss="offcanvas">
                            <i class="fa fa-close"></i>
                        </a>
{#                        <a class="btn btn-icon-toggle btn-default-light pull-right" href="#offcanvas-search" data-toggle="offcanvas" data-backdrop="false">#}
{#                            <i class="fa fa-arrow-left"></i>#}
{#                        </a>#}
                    </div>
                    <form class="form">
                        <div class="form-group floating-label">
                            <textarea name="sidebarChatMessage" id="sidebarChatMessage" class="form-control autosize" rows="1"></textarea>
                            <label for="sidebarChatMessage">Leave a message</label>
                        </div>
                    </form>
                </div>

                <div class="offcanvas-body">
                    <ul class="list-chats">
                        <li>
                            <div class="chat">
                                <div class="chat-avatar"><img class="img-circle" src="/static/common/img/user_avatar.png" alt="" /></div>
                                <div class="chat-body">
                                    Yes, it is indeed very beautiful.
                                    <small>10:03 pm</small>
                                </div>
                            </div><!--end .chat -->
                        </li>
                    </ul>
                </div><!--end .offcanvas-body -->
            </div><!--end .offcanvas-pane -->
            <!-- END OFFCANVAS CHAT -->
        </div><!--end .offcanvas-->
		<!-- END OFFCANVAS RIGHT -->
        {% endifequal %}

	</div>
	<!--end #base-->
	<!-- END BASE -->

    <input type="hidden" id="check_access_project" value="{{ check_access }}">

     <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/datatables/dmedia/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendor/datatables/dmedia/js/dataTables.bootstrap.js"></script>
    <script src="/static/vendor/datatables/extensions/ColVis/js/dataTables.colVis.js"></script>
{#    <script src="/static/vendor/StickyTableHeaders/js/jquery.ba-throttle-debounce.min.js"></script>#}
{#    <script src="/static/vendor/StickyTableHeaders/js/jquery.stickyheader.js"></script>#}


    <script src="/static/common/js/app.js"></script>
    <script src="/static/common/js/nav.js"></script>
    <script src="/static/common/js/tables.js"></script>
    <script src="/static/common/js/lemmon-slider.js"></script>



    <script>
        $(function () {
           var check_access_project = $("#check_access_project").val();

            if (check_access_project == "False")
            {
                window.location.href = "/";
            }


           $('[data-toggle="tooltip"]').tooltip();
        });

        var getUrlParameter = function getUrlParameter(sParam) {
            var sPageURL = decodeURIComponent(window.location.search.substring(1)),
                sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');

                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : sParameterName[1];
                }
            }
        };

        function zoom() {
            document.body.style.zoom = "90%"
        }

        function print(messages)
        {
            var message = messages.split(",");

            console.log(message);

            var message_to_print = '';
            $(message).each(function () {
                console.log($(this).toString());
                message_to_print += $(this).toString();
            });
            console.log(message_to_print);
        }
    </script>

	<!-- BEGIN JAVASCRIPT -->
    <script src="/static/common/js/jquery.colorbox.js"></script>
    <script src="/static/common/libs/libs/spin.js/spin.min.js"></script>
    <script src="/static/common/libs/libs/autosize/jquery.autosize.min.js"></script>
    <script src="/static/common/js/core_static.js"></script>
    <script src="/static/common/js/Demo.js"></script>

	</body>


    <script>
        $(function () {
           $('div.modal-header:visible').click(function () {
               waitingDialog.hide();
           });
        });
    </script>
</html>